'use strict';

const { requireConfirmedAuth } = require('../_lib/confirmed-auth.js');
const {
  jsonBody, isUuid, checkDirectorEnabled, getDirectorEntitlement
} = require('../_lib/h3-director-store.js');
const { moderateDirectorPrompt } = require('../_lib/h3-director-moderation.js');
const {
  PROMPT_MAX_CHARS, ALLOWED_PLANS, buildDirectorProviderPrompt
} = require('../_lib/h3-director-config.js');

module.exports = async function handler(req, res) {
  res.setHeader('Cache-Control', 'no-store');
  if (req.method !== 'POST') return res.status(405).json({ ok: false, error: 'method_not_allowed' });
  const auth = await requireConfirmedAuth(req);
  if (!auth.ok) return res.status(auth.status).json(auth.body);
  const body = jsonBody(req);
  const sessionId = String(body.sessionId || '').trim();
  const commandId = String(body.commandId || '').trim();
  const prompt = String(body.prompt || '').trim();
  if (!isUuid(sessionId)) return res.status(400).json({ ok: false, error: 'invalid_session_id' });
  if (!isUuid(commandId)) return res.status(400).json({ ok: false, error: 'invalid_command_id' });
  if (prompt.length < 1 || prompt.length > PROMPT_MAX_CHARS) {
    return res.status(400).json({ ok: false, error: 'invalid_prompt' });
  }

  const { data: session, error } = await auth.supabase.from('h3_director_sessions')
    .select('id,status,prompt_version,expires_at,input_mode,identity_anchor_prompt,anchor_bound_at')
    .eq('id', sessionId).eq('user_id', auth.user.id).maybeSingle();
  if (error) return res.status(500).json({ ok: false, error: 'session_lookup_failed' });
  if (!session) return res.status(404).json({ ok: false, error: 'session_not_found' });
  if (!['connecting', 'live'].includes(session.status) || Date.now() >= Date.parse(String(session.expires_at || ''))) {
    return res.status(409).json({ ok: false, error: 'session_not_live' });
  }
  if (session.input_mode === 'image' && (!session.anchor_bound_at || !session.identity_anchor_prompt)) {
    return res.status(409).json({ ok: false, error: 'identity_anchor_unavailable' });
  }

  // Same Preview-only relaxation as start-session.js / heartbeat.js.
  const isVercelPreview = process.env.VERCEL_ENV === 'preview';

  const [control, entitlement] = await Promise.all([
    checkDirectorEnabled(auth.supabase),
    getDirectorEntitlement(auth.supabase, auth.user.id, ALLOWED_PLANS)
  ]);
  if (
    (!control.ok && !isVercelPreview) ||
    !entitlement.ok ||
    !entitlement.allowed ||
    entitlement.accountStatus !== 'active'
  ) {
    return res.status(403).json({ ok: false, error: entitlement.accountStatus !== 'active' ? 'account_restricted' : 'access_revoked' });
  }

  const moderation = await moderateDirectorPrompt(prompt);
  if (!moderation.ok) return res.status(503).json({ ok: false, error: 'content_safety_unavailable' });
  if (!moderation.allow) return res.status(422).json({ ok: false, error: 'content_not_allowed' });

  // The version increment and command-ledger insert happen in one database
  // transaction. commandId is generated by the browser and makes an HTTP
  // retry idempotent: the same command never receives a second version.
  const { data: approvedRows, error: approveError } = await auth.supabase.rpc(
    'approve_h3_director_prompt_atomic',
    {
      p_session_id: sessionId,
      p_user_id: auth.user.id,
      p_command_id: commandId,
      p_prompt: prompt
    }
  );
  if (approveError) return res.status(500).json({ ok: false, error: 'prompt_state_failed' });
  const approved = Array.isArray(approvedRows) ? approvedRows[0] : approvedRows;
  if (!approved?.command_id || !approved?.prompt_version) {
    const code = approved?.code || 'prompt_state_failed';
    const status = code === 'session_not_found' ? 404
      : ['session_not_live', 'command_id_conflict'].includes(code) ? 409
        : 400;
    return res.status(status).json({ ok: false, error: code });
  }
  return res.status(200).json({
    ok: true,
    commandId: approved.command_id,
    prompt,
    providerPrompt: buildDirectorProviderPrompt(prompt, session.identity_anchor_prompt),
    promptVersion: Number(approved.prompt_version),
    replay: approved.replay === true
  });
};
